name: CI

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Install make
        run: choco install make --yes --no-progress
      - name: Lint, test and build
        run: make lint test build
